remove qq related from core and sdk
cc004/autopcr pull request #153
Opened 2024-11-05 14:47 UTC by cc004

2024-11-06 15:45 UTC, Lanly109 commented on autopcr/module/validator.py
> +        validate_dict[qq].append(ValidateInfo(status="ok"))
这个，所有过码方式都得有这个，不仅仅只有手动过码
即成功登录后才加这个ok的状态，表示成功登录

2024-11-07 08:37 UTC, Lanly109 commented on autopcr/http_server/httpserver.py
> +            result.client.session.sdk.captchaVerifier = create_validator(qid)
登录入口除了httpserver，还有插件的server和定时的cron，这样子的话，就只有httpserver支持本地和手动过码，而插件和定时的只有默认构造参数里的远程过码了？

2024-11-07 09:39 UTC, Lanly109 commented on autopcr/http_server/validator.py
> +            result.client.session.sdk.post_login = post_login
思考，accountmgr貌似还没有client，得accountmgr的load创建出来的account才有client
usermgr是全局的，accountmgr是某个qq下的，account才是某个qq下的某个账号（

2024-11-07 09:43 UTC, cc004 commented on autopcr/http_server/validator.py
> +            result.client.session.sdk.post_login = post_login
改的是accountmgr的load 好像没问题吧

2024-11-07 09:45 UTC, Lanly109 commented on autopcr/http_server/validator.py
> +            result.client.session.sdk.post_login = post_login
原来有两层，没事了，看走眼了

2024-11-08 02:33 UTC, Lanly109 requested changes

2024-11-08 02:33 UTC, Lanly109 commented on autopcr/sdk/bsgamesdk.py
> +        captch_done=await make_captch()
这里少了client参数传入

2024-11-08 15:55 UTC, Lanly109 approved these changes

2024-11-08 16:11 UTC, Lanly109 commented on autopcr/http_server/validator.py
> +    async def validator(client: sdkclient):
登录时的调用入口，还有client

2024-11-08 16:11 UTC, Lanly109 commented on autopcr/http_server/validator.py
> +            info = await validator(client)
这里还有参数client，实际的Validator的参数空了（

2024-11-08 16:20 UTC, cca2878 commented on autopcr/sdk/bsgamesdk.py
Bsdkv3只要把httpx换成aiorequest应该可以无缝挪过来。不过一些涉及到httpx的特性（headers）可能处理有点麻烦？

2024-11-08 16:45 UTC, cc004 commented on autopcr/sdk/bsgamesdk.py
我觉得只需要正常实现async def login(...)的接口就够了

2024-11-10 03:34 UTC, Lanly109 commented on autopcr/constants.py
> +CLIENT_POOL_SIZE_MAX = 100
判断定时任务会创建pcrclient，因而会大幅刷新client pool，如果账号数大于CLIENT_POOL_SIZE_MAX，会导致缓存实际上只有半分钟

2024-11-11 07:04 UTC, cc004 commented on autopcr/constants.py
> +CLIENT_POOL_SIZE_MAX = 100
这。。。这是计算机缓存问题吧 那就把max调成9999999？

2024-11-12 01:32 UTC, Lanly109 commented on autopcr/constants.py
> +CLIENT_POOL_SIZE_MAX = 100
判断定时会创建account实例，就会初始化client。遍历所有账号判断定时就会创建所有账号的client，基本client pool就变了样了
https://github.com/cc004/autopcr/blob/1cacabf48216fb2df0378b8250546a2d5bbd1e7d/autopcr/module/crons.py#L45
感觉要么改一下创client的逻辑，要么整一个中心管理的cron实例

2024-11-12 09:06 UTC, Lanly109 commented on autopcr/module/clientpool.py
> +    last_access: int
没有默认值吗，我看第一次创建时没有设置last_access，第二次访问到40行时会抛出 没有last_access这个属性

2024-11-12 14:57 UTC, Lanly109 commented on autopcr/core/sessionmgr.py
> +                return await self.request(request, next)
现在client pool不保证同账号是同一个实例了，为了防止两个账号疯狂互顶，给重登加个次数限制？

2024-11-13 02:16 UTC, Lanly109 commented on autopcr/module/clientpool.py
> +        key = (channel, account.username)
相同的channel和username就视为同一个实例是否妥当？
尽管channel和username相同，但由于可能在不同的qq+alias下，导致其config不一样，如此一来可能会出现config key写冲突和错乱
为避免这种情况，外层account的lock的key应该和这里的key保持一致之类的

2024-11-18 08:00 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +        self.active_uids.remove(client.session)
应该是`self.active_uids.remove(client.uid)`？

2024-11-18 08:00 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +        assert isinstance(self._container, PoolClientWrapper)
没有`return`的值吗

2024-11-18 08:00 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +            raise RuntimeError('用户的另一项请求正在进行中')
从pool里取cache，发现失效了，重登，感觉会从20行触发到这个？

2024-11-18 08:00 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +        if pool_key in self._pool:
貌似还是会存在不同qq+alias对应同一个账号相互互顶的行为，是期望现象吗？

2024-11-18 08:31 UTC, cc004 commented on autopcr/core/clientpool.py
> +        if pool_key in self._pool:
这个应该会在sdk login里面根据uid直接抛出异常

2024-11-19 01:56 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +                return await self.request(request, next)
如果这里调用再次6002，此处将不会再捕获到这次的ApiException错误，而是继续往上抛。
如果此处请求成功，retry将被置为0。从而导致retry的取值只有0或1，`SESSION_ERROR_MAX_RETRY`形同虚设？
`SESSION_ERROR_MAX_RETRY`指的是一次请求重登的次数，还是指一系列任务的重登次数？
这里应该改成`while self.retry < SESSION_ERROR_MAX_RETRY:`的形式？

2024-11-19 01:56 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +            raise RuntimeError('用户的另一项请求正在进行中')
`RuntimeError`改成`PanicError`？后者能让整个任务停止下来，前者暂时没有特别处理，只会将当前任务视为发生错误而跳过，继续执行下一个任务

2024-11-19 02:07 UTC, cc004 commented on autopcr/core/clientpool.py
> +                return await self.request(request, next)
这里用的是self不是next

2024-11-19 02:37 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +                return await self.request(request, next)
没事了

2024-11-19 12:28 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +            assert item.client.uid not in self.active_uids
同个qq+alias连续两次调用，第二个alias会在account层的lock变为串行，但当第一次执行完，在第二次执行时，如果遇到定时检查，该assert不成立。
同时连续两次调用时，后一次的client并未继承前一次的client，而是全新client，会重新登录

2024-11-19 12:37 UTC, Lanly109 commented on autopcr/module/modulemgr.py
> +        await self.client.__aenter__()
93行加载的配置，这里又清掉了（

2024-11-20 02:13 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +        self.active_uids[client.uid] = client_key
这里更新下`last access`？`get client`在`cron`里会调用，在那里更新怕是会每分钟刷新一次

2024-11-21 09:40 UTC, Lanly109 commented on autopcr/module/accountmgr.py
> +        self._lck = Account._account_locks.get(self._filename, Lock())
get如果是空的就使用默认值，但不会set？次次请求都是新的lock？

2024-11-21 09:40 UTC, Lanly109 commented on autopcr/module/accountmgr.py
> +        self._lck = AccountManager._user_locks.get(self.root, Lock())
这里也是

2024-11-22 06:38 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +        if not client.logged: # client session expired and not successfully recovered
如果恰好最后一个功能 服务器返回出错，导致not logged，就不会放回pool，同时active_uids也不会移除，导致最后无法登录了

2024-11-22 07:10 UTC, Lanly109 commented
多账号同时跑时，偶发请求参数错乱的现象，尚不知原因

2024-11-22 07:52 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +        self.active_uids.pop(client.uid)
不同qq+alias的A、B对应同一个账号
A调任务，B调，被74行ban了，然后回来put in pool，把activate uid pop了，因为没logged，所以不放回去
此时B再迅速调一次，优先抵达74，把client_key改成自己的，然后A才发下一次请求，然后被74 ban了

2024-11-23 05:21 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +        if self.active_uids.get(client.uid, -1) != client.uid:
论冲冲在写的代码时的精神状态（？
`if self.active_uids.get(client.uid, -1) != id(client)`

2024-12-09 03:57 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +        self.active_uids.pop(client.uid)
修改账号配置（比如帐密、配置项）时，是非readonly，但是又不登陆，因此client.uid是None，没有_on_sdk_login，所以active_uids会抛出keyerror。
貌似账号有三种情况：仅阅读、仅修改配置、执行（需要client）？

2024-12-10 01:52 UTC, Lanly109 commented on autopcr/core/clientpool.py
> +            client.session.sdk = sdk
获取缓存的client，先请求一次`is_first=0`的`HomeIndexRequest`，以刷新必要数据，好像有函数`client.refresh()`。
同时，如果是昨日的client（`now > daily_reset_time`），应重登。

2024-12-13 04:00 UTC, merged